HW-1: class Process implementation.
iam-aberman/AdvCpp pull request #1
Opened 2020-10-09 14:42 UTC by iam-aberman

2020-10-10 13:27 UTC, a-badin requested changes

2020-10-10 13:27 UTC, a-badin commented on process.h
> +    int fork_pid_;
pid_t

2020-10-10 13:27 UTC, a-badin commented on process.cpp
> +    if (pipe(parent_to_child_) == -1) {
Хорошоая практика ::

2020-10-10 13:27 UTC, a-badin commented on process.cpp
> +        execvp(args[0], args);
::exit(?)

2020-10-10 13:27 UTC, a-badin commented on process.cpp
> +        char* args[2] = {exec_path.data(), nullptr};
`char *args[2] -> std::vector<char*>`

2020-10-10 13:27 UTC, a-badin commented on process.h
> +    int parent_to_child_[2];
Только 2

2020-10-10 13:27 UTC, a-badin commented on process.cpp
> +        step = ::write(parent_to_child_[1], static_cast<const char*>(data) + written, 1);
свой write

2020-10-10 13:27 UTC, a-badin commented on process.cpp
> +        step = ::read(child_to_parent_[0], static_cast<char*>(data) + read, 1);
не читаем по байту

2020-10-10 13:27 UTC, a-badin commented on process.cpp
> +            read += static_cast<size_t>(step);
если 0 то ошибка

2020-10-10 13:27 UTC, a-badin commented on process.cpp
> +        int child_state = waitpid(fork_pid_, &status, WNOHANG);
посылаем SIGINT и ждем waitpid

2020-10-10 13:27 UTC, a-badin commented on process.cpp
> +#define PIPE_SIZE 2
Не пользоваться define, constexpr

2020-10-13 15:01 UTC, a-badin requested changes
Похоже что все аккуратно, не хотите сделать на выбор или передачу произвольных аргументов в конструктор Process или получение ошибки exec в конструкторе на макс балл?

2020-10-13 21:23 UTC, iam-aberman commented on process.h
> +    explicit Process(std::vector<std::string> arguments);
Передаю вектор аргументов по значению, так как execvp потребует неконстантные указатели. Передай я вектор аргументов по константной ссылке, пришлось бы делать его копию/пользоваться const_cast. Я предположил, что передать по значению рационально - будет одна копия объекта, или вообще сработает Copy Elision.

2020-10-15 10:58 UTC, a-badin approved these changes
Вполне аккуратненько получилось

2020-10-15 10:58 UTC, a-badin commented on process.cpp
> +        throw std::runtime_error("EXEC_FAILED");
вот тут лучше сделать exit, потому что если это исключение где-то поймают наверху по стеку - то у вас будет полноценная копия вашего родителя, который теперь живет своей жизнью. Это скорее всего не то поведение, которое ожидается

2020-10-15 10:58 UTC, a-badin commented on process.cpp
> +        for (size_t i = 0; i < arguments.size(); ++i) {
Пользуйтесь удобными итераторами и методами
```
for(std::string& arg : arguments) {
    args.push_back(arg.data());
}

```

2020-10-15 10:58 UTC, a-badin commented on process.cpp
> +                throw std::invalid_argument("BAD_ARGV_FOR_EXEC");
тут тоже лучше exit, чтобы дочерний процесс гарантированно умирал в случае ошибки - исключение можно поймать

2020-10-15 10:58 UTC, a-badin commented on process.cpp
> +        std::vector<char*> args(arguments.size() + 1);
Если просто пользоваться push_back вы сделаете код читабельнее, экономия 1-2 аллокации памяти этого не стоит

2020-10-15 10:58 UTC, a-badin commented on process.h
> +    explicit Process(std::vector<std::string> arguments);
Все аргументированно, я с вами согласен.
Но опять же строго говоря вам интерфейс зафиксировали, хоть и работать все равно будет.
А копировать его в аргументах или внутри тела функции разницы нет копия и так и так будет одна.

PS. path я бы оставил первым параметром, потому что иначе нарушается сигнатура метода. Плюс path обязателен

2020-10-15 10:59 UTC, merged