HW-2 Logger
iam-aberman/AdvCpp pull request #2
Opened 2020-10-16 13:31 UTC by iam-aberman

2020-10-20 15:04 UTC, Kapitonov requested changes

2020-10-22 10:49 UTC, Kapitonov requested changes

2020-10-22 10:49 UTC, Kapitonov commented on HW-2/Log/include/base_logger.h
> +#include <map>
Теперь это лишнее

2020-10-22 10:49 UTC, Kapitonov commented on HW-2/Log/source/file_logger.cpp
> +        if (level >= get_level()) {
Функции log имеют идентичную реализацию, предлагаю использовать что все ваши потоки подтипы std::ostream и вынести реализацию в базовый класс. Возможно придется завести какие-то служебные вещи, но мы избавимся от дублирования кода.

2020-10-22 10:49 UTC, Kapitonov commented on HW-2/Log/source/log_singleton.cpp
> +        logger_.reset(logger.release());
Еще лучше logger_.swap(logger);

2020-10-22 21:33 UTC, iam-aberman commented on HW-2/Log/CMakeLists.txt
> -                    source/stdout_logger.cpp
В силу получившейся краткости этих файлов, удалил и перенес все в заголовочные.

2020-10-22 21:34 UTC, iam-aberman commented on HW-2/Log/include/base_logger.h
> +        explicit BaseLogger(std::ostream& os, Level level = Level::INFO);
Конструктор сделан приватным, чтобы нельзя было в явном виде создать экземпляр базового класса.

2020-10-22 21:35 UTC, iam-aberman commented
В базовый класс BaseLogger добавил std::ostream& output_. Это позволило вытащить методы flush и log на базовый уровень.

2020-10-26 06:56 UTC, Kapitonov requested changes

2020-10-26 06:56 UTC, Kapitonov commented on HW-2/Log/include/file_logger.h
> +            output_file_.close();
А разве деструктор ofstream не закроет фал?

2020-10-26 06:56 UTC, Kapitonov commented on HW-2/Log/include/base_logger.h
> +        virtual ~BaseLogger() = default;
Предлагаю флашить, чтобы все записалось в поток.

2020-10-26 16:44 UTC, iam-aberman commented
Если вы будете делать merge с основной веткой, пожалуйста, разрешите конфликт - он какой-то странный. Там идентичные файлы, никакой разницы между ними нет, на самом деле.

2020-11-02 08:03 UTC, merged