Lib tcp
iam-aberman/AdvCpp pull request #3
Opened 2020-10-29 23:14 UTC by iam-aberman

Не смог придумать примеров, чтобы показать работу библиотеки. В моем понимании, класс Server, описанный в домашнем задании, сам по себе не особо полезен, ведь через соединения с ним особо ничего нельзя сделать. Полагаю, это можно использовать с связке, скажем, с какой-то базой данных, тогда можно создать под нее сервер и через соединения с ним посылать запросы, обрабатывать их и отправлять клиенту ответы.

2020-11-03 16:27 UTC, Kapitonov requested changes
Надо завести 2 класса исключений: для дескрипторов и для соединений.

2020-11-03 16:27 UTC, Kapitonov commented on HW-3/tcp/source/connection.cpp
> +        if (connection_status < 0) {
Не лучше на сам connect навесить if?

2020-11-03 16:27 UTC, Kapitonov commented on HW-3/tcp/source/connection.cpp
> +                throw std::runtime_error("bad_read");
Лучше конкретизировать в сообщении, что это за обшибка.

2020-11-03 16:27 UTC, Kapitonov commented on HW-3/tcp/source/descriptor.cpp
> +    if (fd >= 0) {
Вы скорее всего перепутали условие.

2020-11-03 16:27 UTC, Kapitonov commented on HW-3/tcp/source/descriptor.cpp
> +    fd_ = fd >= 0 ? fd : -1;
А закрыть старый дескритор? Иначе утечка.

2020-11-03 16:27 UTC, Kapitonov commented on HW-3/tcp/source/descriptor.cpp
> +    fd_ = tmp.fd_;
Можно заиспользовать std::swap, что укоротит код. Тогда при уничтожении временного дескриптора, старый закроется.

2020-11-05 16:25 UTC, iam-aberman commented on HW-3/tcp/source/descriptor.cpp
> +    fd_ = tmp.fd_;
Использование std::swap в этом месте почему-то приводит к SegFaullt: 11

2020-11-11 23:43 UTC, Kapitonov commented on HW-3/tcp/source/descriptor.cpp
> +    fd_ = tmp.fd_;
А вы что с чем свапали?

2020-11-11 23:43 UTC, Kapitonov requested changes
Поправьте все замечания.

2020-11-12 15:49 UTC, iam-aberman commented on HW-3/tcp/source/descriptor.cpp
> +    fd_ = tmp.fd_;
Все, я понял свою ошибку. Я делал `std::swap(*this, tmp),` а надо было `std::swap(this->fd_, tmp.fd_)`. Тогда у наших объектов класса Дескриптор поменяются числа, у tmp вызовется деструктор и закроет старый дескриптор. Крутой трюк, спасибо!

2020-11-19 02:50 UTC, Kapitonov requested changes
После переименования можно сливать.

2020-11-19 02:50 UTC, Kapitonov commented on HW-3/tcp/include/server.h
> +
Пустые строки.

2020-11-19 02:50 UTC, Kapitonov commented on HW-3/tcp/include/descriptor.h
> +
Лишние пустые строки.

2020-11-19 17:23 UTC, iam-aberman commented
После ревью А. Капитонова

2020-11-19 17:23 UTC, merged