HW-4 SharedMap
iam-aberman/AdvCpp pull request #4
Opened 2020-11-08 21:20 UTC by iam-aberman

2020-11-11 17:47 UTC, a-badin requested changes

2020-11-11 17:47 UTC, a-badin commented on HW-4/CMakeLists.txt
> +set(CMAKE_EXE_LINKER_FLAGS -pthread)
Лучше 
```
find_package(Threads)
target_link_libraries(main ${CMAKE_THREAD_LIBS_INIT})
```

2020-11-11 17:47 UTC, a-badin commented on HW-4/shared_memory/include/shared_map.h
> +        using Key_ = std::conditional_t<std::is_pod_v<Key>, Key, SharedString>;
is_pod пометили deprecated, используйте is_trivial

2020-11-11 17:47 UTC, a-badin commented on HW-4/shared_memory/include/shared_map.h
> +        using Value_ = std::conditional_t<std::is_pod_v<Value>, Value, SharedString>;
Все же более конкретный случай будет привязаться к std::string в SharedString

2020-11-11 17:47 UTC, a-badin commented on HW-4/shared_memory/include/shared_map.h
> +        using Node  = std::pair<Key_, Value_>;
std::pair<const Key_, Value_>

2020-11-11 17:47 UTC, a-badin commented on HW-4/shared_memory/include/shared_memory_map.h
> +        MemoryMap(size_t size);
explicit

2020-11-11 17:47 UTC, a-badin commented on HW-4/shared_memory/include/shmem_exception.h
> +    class semaphore_error : public std::runtime_error {
типы назыаются с большой буквы или как в C заканчиваются на _t

2020-11-11 17:47 UTC, a-badin commented on HW-4/shared_memory/include/shmem_exception.h
> +    class mem_map_error : public std::runtime_error {
Ваши исключения лучше отнаследовать от одного вашего общего родителя

2020-11-11 17:47 UTC, a-badin commented on HW-4/shared_memory/include/shared_map.h
> +        auto* state = new (static_cast<char*>(memory_.get()) + sizeof(Semaphore)) ShMemState;
Можно было сразу сделать, чтобы memory_.get() возвращал char*

2020-11-11 17:47 UTC, a-badin commented on HW-4/shared_memory/include/shared_map.h
> +        auto* used_blocks_table = static_cast<char*>(memory_.get()) +
auto и char даже число знаков одинаковое. auto ухудшает читаемость кода, его сделали для сильно вложенных типов, например, итераторов

2020-11-11 17:47 UTC, a-badin commented on HW-4/shared_memory/include/shared_map.h
> +            return ret_value;
почему тогда не return map_->at(get_key_(key)) должно сработать

2020-11-11 17:47 UTC, a-badin commented on HW-4/shared_memory/include/shared_map.h
> +    typename SharedMap<Key, Value>::Key_ SharedMap<Key, Value>::get_key_(const Key& key) const {
Должно получиться сделать один метод и на key и на value, тут можно обойтись даже без constexpr, хватит обычной перегрузки

2020-11-12 14:47 UTC, iam-aberman commented on HW-4/shared_memory/include/shared_map.h
> +            return ret_value;
В случае со строкой без явного преобразования типа код не компилируется. Я убрал auto ret_value, сделал как вы сказали с добавлением каста.

2020-11-17 17:29 UTC, a-badin approved these changes

2020-11-17 17:29 UTC, merged