HW-5 Service
iam-aberman/AdvCpp pull request #5
Opened 2020-11-19 17:32 UTC by iam-aberman

Простой пример использования. Делается форк. Процесс-ребенок посылает строчку 'строка' (без кавычек), сервер возвращает строку '{ строка }'. Если приходит EPOLLRDHUP, Listener кидает исключение, чтобы выйти из вечного цикла в методе run().

2020-11-20 18:54 UTC, a-badin requested changes

2020-11-20 18:54 UTC, a-badin commented on HW-5/net_lib/source/service.cpp
> +    void Service::set_listener(std::unique_ptr<IServiceListener>&& listener) {
std::unique_ptr

2020-11-20 18:54 UTC, a-badin commented on HW-5/net_lib/include/service.h
> +        void set_listener(std::unique_ptr<IServiceListener>&& listener);
weak или raw

2020-11-20 18:54 UTC, a-badin commented on HW-5/net_lib/include/service.h
> +        static void subscribe_to(BufferedConnection& con, uint32_t events);
почему static

2020-11-20 18:54 UTC, a-badin commented on HW-5/net_lib/include/net_epoll.h
> +        size_t max_size_;
Нужно уметь менять

2020-11-20 18:54 UTC, a-badin commented on HW-5/net_lib/source/net_epoll.cpp
> +}
} // namespace net

2020-11-23 18:42 UTC, a-badin requested changes
Нужно сделать возможность закрыть соединение со стороны сервера, например, в колбеке. Сейчас если закрыть соединение, например, через close() оно останется в мапе

2020-11-24 12:41 UTC, iam-aberman commented
Добавил сервису метод, позволяющий закрыть соединение, удалив его из набора, и задумался. Для того, чтобы использовать этот метод в коллебеке, нам придется, видимо, делать Listener, который должен хранить в себе ссылку/указатель на наш сервис, чтобы мы могли вызвать этот метод. Так?

2020-12-02 08:27 UTC, a-badin approved these changes
Скорее всего ваш итоговый сервер будет иметь следующий вид:
```
class SuperManagerClass : public IServiceListener,
                              public std::enable_shared_from_this<SuperManagerClass> {
  void OnReadAvailible(BufferedConnection& con) override {
    con.write("bye-bye");
    service_.close_connection(con);
  }

  void run() {
    service_.setListener(shared_from_this());
    service_.run();
  }
...
private:
  net::Service service_;
};

int main() {
  auto server = std::make_shared<SuperManagerClass>();
  server.run();
}
```

Я накидал много замечаний по прошлым классам, лучше их поправить в след работах

2020-12-02 08:27 UTC, a-badin commented on HW-5/net_lib/source/net_epoll.cpp
> +    EPoll::EPoll(size_t max) : max_size_(max){
Сейчас у вас сначала вызывается конструктор по-умолчанию для epoll_fd, а затем оператор присваивания.
Лучше сразу проинициализировать в member initializer list, как с max_size_ или передать дексриптор через set_fd

2020-12-02 08:27 UTC, a-badin commented on HW-5/net_lib/source/net_epoll.cpp
> +        }
лучше кидать ошибку, чем игнорировать неправильный параметр

2020-12-02 08:27 UTC, a-badin commented on HW-5/net_lib/source/net_epoll.cpp
> +    void EPoll::add(Descriptor& fd, uint32_t events) {
const Descriptor&

2020-12-02 08:27 UTC, a-badin commented on HW-5/net_lib/source/net_epoll.cpp
> +    void EPoll::mod(Descriptor& fd, uint32_t events) {
const Descriptor&

2020-12-02 08:27 UTC, a-badin commented on HW-5/net_lib/source/net_epoll.cpp
> +    void EPoll::del(Descriptor& fd) {
const Descriptor&

2020-12-02 08:27 UTC, a-badin commented on HW-5/net_lib/source/buffered_connection.cpp
> +    connection_(std::move(tmp)), epoll_(epoll), epoll_flags_(0u)
А вот epoll на nullptr лучше проверить

2020-12-02 08:27 UTC, a-badin commented on HW-5/net_lib/source/buffered_connection.cpp
> +        dest = read_buf_;
dest = std::move(read_buf_); в одну строчку и без копирования

2020-12-02 08:27 UTC, a-badin commented on HW-5/net_lib/source/buffered_connection.cpp
> +                read_buf_.data() + (read_buf_.size() - DEF_BUF_SIZE),
выделите ` read_buf_.data() + (read_buf_.size() - DEF_BUF_SIZE)` в отделньую переменную, и у вас будет действие в 1 строчку

2020-12-02 08:27 UTC, a-badin commented on HW-5/net_lib/source/buffered_connection.cpp
> +        }
нет return' а

2020-12-02 08:27 UTC, a-badin commented on HW-5/net_lib/source/service.cpp
> +            for (auto& event : ret_events) {
не auto а epoll_event

2020-12-02 08:28 UTC, merged

2020-12-03 16:47 UTC, iam-aberman commented on HW-5/net_lib/source/buffered_connection.cpp
> +        dest = read_buf_;
Можно ли пользоваться объектами после того, как из них был сделан `std::move`?